version: '2'

services:
  sonarqube:
    image: sonarqube
    ports:
      - '9000:9000'
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - /tmp/sonarq-conf/sonarqube_conf:/opt/sonarqube/conf
      - /tmp/sonarq-conf/sonarqube_data:/opt/sonarqube/data
      - /tmp/sonarq-conf/sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
       soft: 65536
       hard: 65536
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /tmp/sonarq-conf/postgresql:/var/lib/postgresql
      - /tmp/sonarq-conf/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge